INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('LPRODUCTID', 'LABELERNAME', 'PRODUCTID', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('ELAC0002', 'Eli Lilly and Company', '0002', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('SS0003', 'E.R. Squibb & Sons, L.L.C.', '0003', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('G0004', 'Genentech, Inc.', '0004', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('WPDOWHCASOP0005', 'Wyeth Pharmaceutical Division of Wyeth Holdings Corporation, a subsidiary of Pfizer Inc.', '0005', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('MSD0006', 'Merck Sharp & Dohme Corp.', '0006', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('GL0007', 'GlaxoSmithKline LLC', '0007', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('WPC0008', 'Wyeth Pharmaceuticals Company', '0008', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('PAUC0009', 'Pharmacia and Upjohn Company', '0009', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('SS0015', 'E.R. Squibb & Sons, L.L.C.', '0015', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('M0019', 'Mallinckrodt Inc.', '0019', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('A0023', 'Allergan, Inc.', '0023', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('SAL0024', 'sanofi-aventis U.S. LLC', '0024', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('SLDOPI0025', 'G.D. Searle LLC Division of Pfizer Inc', '0025', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('BHL0026', 'Bayer HealthCare LLC', '0026', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('GL0029', 'GlaxoSmithKline LLC', '0029', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('RDOW0031', 'Richmond Division of Wyeth', '0031', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('AP0032', 'Abbott Products, Inc.', '0032', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('MP0037', 'Meda Pharmaceuticals Inc.', '0037', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('SAL0039', 'Sanofi-Aventis U.S. LLC', '0039', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('OBL0041', 'Oral-B Laboratories', '0041', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('NCH0043', 'Novartis Consumer Health', '0043', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('WPIASOP0046', 'Wyeth Pharmaceuticals Inc., a subsidiary of Pfizer Inc.', '0046', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('R0049', 'Roerig', '0049', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('A0051', 'AbbVie Inc.', '0051', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('OU0052', 'Organon USA Inc.', '0052', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('CBL0053', 'CSL Behring LLC', '0053', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('RLI0054', 'Roxane Laboratories, Inc', '0054', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('BMSPC0056', 'Bristol-Myers Squibb Pharma Company', '0056', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('OMJP0062', 'Ortho-McNeil Janssen Pharmaceuticals, Inc.', '0062', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('HL0064', 'HEALTHPOINT, LTD', '0064', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('AL0065', 'Alcon Laboratories, Inc.', '0065', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('DL0066', 'Dermik Laboratories', '0066', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('NCH0067', 'Novartis Consumer Health, Inc.', '0067', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('SAL0068', 'sanofi-aventis U.S. LLC', '0068', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('PLDP0069', 'Pfizer Laboratories Div Pfizer Inc.', '0069', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('PDDOPI0071', 'Parke-Davis Div of Pfizer Inc', '0071', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('A0074', 'AbbVie Inc.', '0074', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('SAL0075', 'sanofi-aventis U.S. LLC', '0075', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('SPL0076', 'Star Pharmaceuticals, LLC', '0076', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('NPC0078', 'Novartis Pharmaceuticals Corporation', '0078', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('SC0085', 'Schering Corporation', '0085', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('BMSC0087', 'Bristol-Myers Squibb Company', '0087', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('SAL0088', 'sanofi-aventis U.S. LLC', '0088', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('MP00904', 'Major Pharmaceuticals', '00904', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('U0091', 'UCB, Inc.', '0091', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('TPUI0093', 'Teva Pharmaceuticals USA Inc', '0093', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('EPC0095', 'ECR Pharmaceuticals Co., Inc.', '0095', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('PAC0096', 'Person and Covey', '0096', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('LPC0113', 'L Perrigo Company', '0113', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('GPDOIL0115', 'Global Pharmaceuticals, Division of Impax Laboratories Inc.', '0115', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('XL0116', 'Xttirum Laboratories, Inc.', '0116', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('PA0121', 'Pharmaceutical Associates, Inc.', '0121', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('CPC0126', 'Colgate-Palmolive Company', '0126', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('KUPI0131', 'Kremers Urban Pharmaceuticals Inc', '0131', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('FC0132', 'C.B. Fleet Company, Inc.', '0132', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('GCHL0135', 'GlaxoSmithKline Consumer Healthcare LP', '0135', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('RPI0140', 'Roche Products Inc', '0140', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('WWPC0143', 'West-Ward Pharmaceutical Corp', '0143', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('SLI0145', 'Stiefel Laboratories Inc', '0145', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('WCP0149', 'Warner Chilcott Pharmaceuticals Inc.', '0149', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('PN0159', 'PJ Noyes Co. Inc.', '0159', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('WSGZDW0164', 'Weleda A.G. Schwabisch Gmund, Zweigniederlassung der Weled', '0164', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('FADOFP0168', 'E. Fougera & Co. a division of Fougera Pharmaceuticals Inc.', '0168', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('NN0169', 'Novo Nordisk', '0169', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('IP0172', 'IVAX Pharmaceuticals, Inc.', '0172', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('GL0173', 'GlaxoSmithKline LLC', '0173', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('MPC0178', 'Mission Pharmacal Company', '0178', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('KFH0179', 'KAISER FOUNDATION HOSPITALS', '0179', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('GL0182', 'Goldline Laboratories, Inc.', '0182', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('EL0185', 'Eon Labs, Inc.', '0185', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('AL0186', 'AstraZeneca LP', '0186', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('VPI0187', 'Valeant Pharmaceuticals International', '0187', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('WPIASOP0206', 'Wyeth Pharmaceuticals Inc., a subsidiary of Pfizer Inc.', '0206', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('HPI0219', 'Humphreys Pharmacal, Incorporated', '0219', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('LB0220', 'Laboratoires Boiron', '0220', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('KP0224', 'Konsyl Pharmaceuticals, Inc.', '0224', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('BAACI0225', 'BF ASCHER AND CO INC', '0225', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('AEL0228', 'Actavis Elizabeth LLC', '0228', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('MHCUL0234', 'Molnlycke Health Care US, LLC', '0234', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('USL0245', 'Upsher-Smith Laboratories, Inc.', '0245', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('FCP0256', 'Fleming & Company, Pharmaceuticals', '0256', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('FL0258', 'Forest Laboratories', '0258', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('MPL0259', 'Merz Pharmaceuticals, LLC', '0259', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('BM0264', 'B. Braun Medical Inc.', '0264', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('AA0268', 'ALK-Abello, Inc.', '0268', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('BDI0270', 'Bracco Diagnostics Inc', '0270', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('YDMC1L0273', 'Young Dental Manufacturing Co 1, LLC', '0273', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('BHCC0280', 'Bayer HealthCare Consumer Care', '0280', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('SLADOFP0281', 'SAVAGE LABORATORIES, A division of Fougera Pharmaceuticals Inc.', '0281', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('BLP0283', 'Beutlich LP, Pharmaceuticals', '0283', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('FC0288', 'Fluoritab Corporation', '0288', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('DP0295', 'Denison Pharmaceuticals, Inc.', '0295', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('GL0299', 'Galderma Laboratories, L.P.', '0299', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('APL0310', 'AstraZeneca Pharmaceuticals LP', '0310', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('AI0311', 'Almay, Inc', '0311', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('CL0316', 'Crown Laboratories', '0316', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('MMCI0322', 'Merrick Medicine Company, Inc', '0322', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('UG0327', 'United-Guardian, Inc.', '0327', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('BHC0338', 'Baxter Healthcare Corporation', '0338', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('S0362', 'Septodont, Inc.', '0362', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('WC0363', 'Walgreen Company', '0363', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('STPC0372', 'SCOT-TUSSIN Pharmacal Co., Inc.', '0372', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('LL0374', 'Lyne Laboratories, Inc.', '0374', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('MP0378', 'Mylan Pharmaceuticals Inc.', '0378', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('TTC0389', 'The Torrance Company', '0389', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('HHG0395', 'Humco Holding Group, Inc.', '0395', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('HS0404', 'Henry Schein, Inc.', '0404', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('M0406', 'Mallinckrodt, Inc.', '0406', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('GH0407', 'GE Healthcare Inc.', '0407', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('H0409', 'Hospira, Inc.', '0409', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('WC(L0430', 'Warner Chilcott (US), LLC', '0430', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('CP0436', 'Century Pharmaceuticals, Inc.', '0436', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('LP0440', 'Liberty Pharmaceuticals, Inc.', '0440', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('FLI0456', 'Forest Laboratories, Inc', '0456', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('PADONU0462', 'PharmaDerm, A division of Nycomed US Inc.', '0462', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('T0463', 'C.O. Truxton, Inc.', '0463', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('APU0469', 'Astellas Pharma US, Inc.', '0469', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('AMAL0472', 'Actavis Mid Atlantic LLC', '0472', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('PADOFP0482', 'PharmaDerm A division of Fougera Pharmaceuticals Inc.', '0482', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('EP0485', 'EDWARDS PHARMACEUTICAL, INC.', '0485', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('NPC0487', 'Nephron Pharmaceuticals Corporation', '0487', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('FL0496', 'Ferndale Laboratories, Inc.', '0496', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('NSP0498', 'North Safety Products', '0498', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('AR0517', 'American Regent, Inc.', '0517', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('SC0519', 'STERIS Corporation', '0519', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('P0525', 'Pamlab, L.L.C.', '0525', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('LC0527', 'Lannett Company, Inc.', '0527', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('FL0535', 'Forest Laboratories, Inc.', '0535', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('RL0536', 'Rugby Laboratories, Inc.', '0536', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('AP0548', 'Amphastar Pharmaceuticals, Inc.', '0548', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('BL0555', 'Barr Laboratories Inc.', '0555', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('KM0562', 'Kedrion Melville, Inc.', '0562', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('PCH0573', 'Pfizer Consumer Healthcare', '0573', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('PL0574', 'Paddock Laboratories, Inc.', '0574', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('TGRRL0575', 'Teva Global Respiratory Research LLC', '0575', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('BMSHPLC0590', 'Bristol-Myers Squibb Holdings Pharma, Ltd. Liability Company', '0590', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('WL0591', 'Watson Laboratories, Inc.', '0591', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('BIP0597', 'Boehringer Ingelheim Pharmaceuticals, Inc.', '0597', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('QP0603', 'Qualitest Pharmaceutical, Inc.', '0603', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('NHOKIDVL0615', 'NCS HealthCare of KY, Inc dba Vangard Labs', '0615', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('WWP0641', 'West-ward Pharmaceutical Corp.', '0641', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('EL0642', 'Everett Laboratories, Inc.', '0642', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('URL0677', 'United Research Laboratories, Inc.', '0677', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('MP0682', 'Marnel Pharmaceutical, Inc.', '0682', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('D0699', 'DSHealthcare', '0699', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('TPM0703', 'Teva Parenteral Medicines, Inc.', '0703', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('L0713', 'G&W Laboratories, Inc.', '0713', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('NP0722', 'Nexgen Pharma, Inc.', '0722', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('DPC0777', 'Dista Products Company', '0777', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('SI0781', 'Sandoz Inc', '0781', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('FL0785', 'Forest Laboratories, Inc.', '0785', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('C0799', 'Calmoseptine Inc.', '0799', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('P0813', 'Pharmics, Inc.', '0813', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('USL0832', 'Upsher-Smith Laboratories, Inc.', '0832', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('VJ0869', 'Vi Jon', '0869', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('PP0884', 'Pedinol Pharmacal, Inc.', '0884', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('MP0904', 'MAJOR Pharmaceuticals Inc.', '0904', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('AUC0924', 'Acme United Corporation', '0924', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('BHC0941', 'Baxter Healthcare Corporation', '0941', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('FI0942', 'Fenwal Inc', '0942', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('BHC0944', 'Baxter Healthcare Corporation', '0944', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('W0955', 'Winthrop U.S.', '0955', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('AL0998', 'Alcon Laboratories, Inc.', '0998', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('AOC10006', 'Acetylene Oxygen Company', '10006', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('AAGC10014', 'Aero All Gas Company', '10014', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('APAC10018', 'Air Products and Chemicals, Inc.', '10018', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('BHC10019', 'Baxter Healthcare Corporation', '10019', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('OCOADAL10038', 'Organics Corporation of America dba Ambix Laboratories', '10038', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('ABGL10056', 'Access Business Group LLC', '10056', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('OGESI10073', 'Ozarc Gas Equipment Supply Inc', '10073', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('DIL10078', 'Kay's Designs International Limited', '10078', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('AP10096', 'Avon Products, Inc.', '10096', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('CVL10100', 'Canus Vermont LLC', '10100', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('AML10109', 'ACS Medical LLC', '10109', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('CT10122', 'Cornerstone Therapeutics Inc.', '10122', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('MPI10135', 'Marlex Pharmaceuticals Inc', '10135', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('G10139', 'GeneraMedix', '10139', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('AT10144', 'Acorda Therapeutics, Inc.', '10144', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('PPL10147', 'Patriot Pharmaceuticals, LLC', '10147', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('BI10157', 'Blistex Inc', '10157', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('GCHL10158', 'GlaxoSmithKline Consumer Healthcare LP', '10158', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('QHM10163', 'Quality Home Medical, Inc.', '10163', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('ASII10167', 'Air Source Industries Inc', '10167', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('AHI10188', 'Ansell Healthcare Inc', '10188', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('BGPC10189', 'Butler Gas Products Company', '10189', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('RM10191', 'Remedy Makers', '10191', 1, NOW(), 1);
INSERT INTO company (identifier, name, prefix, created_user_id, created_time, modified_user_id) VALUES ('7E10202', '7-Eleven', '10202', 1, NOW(), 1);
